const fakeId = 'fakeId';
const fakeBaseUrl = `/v1/students/${fakeId}`;
const fakeType = 'fakeType';
const fakePath = 'fakePath';
const fakePathUrl = `${fakeBaseUrl}/${fakePath}`;
const fakeDataSchema = {
  properties: {
    type: {
      enum: [fakeType],
    },
    attributes: {
      properties: {
        fakeAttribute1: null,
        fakeAttribute2: null,
        fakeAttribute3: null,
      },
    },
  },
};
const fakeDefinitions = {
  fakeSingleResult: {
    properties: {
      data: fakeDataSchema,
    },
  },
  fakePluralResult: {
    properties: {
      data: {
        type: 'array',
        items: fakeDataSchema,
      },
    },
  },
};
const argsTestCases = [
  {
    isSingle: true,
    expectedResult: 'fakeSingleResult',
    fakeParams: {},
    expectedLink: fakePathUrl,
  },
  {
    isSingle: true,
    expectedResult: 'fakeSingleResult',
    fakeParams: { fakeKey: 'fakeValue' },
    expectedLink: `${fakePathUrl}?fakeKey=fakeValue`,
  },
  {
    isSingle: true,
    expectedResult: 'fakeSingleResult',
    fakeParams: undefined,
    expectedLink: fakePathUrl,
  },
  {
    isSingle: false,
    expectedResult: 'fakePluralResult',
    fakeParams: undefined,
    expectedLink: fakePathUrl,
  },
];
const rawGpaLevels = [
  {
    gpa: '3.96',
    gpaCreditHours: '103',
    gpaType: 'Institution',
    creditHoursAttempted: '107',
    creditHoursEarned: '107',
    creditHoursPassed: '107',
    level: 'Undergraduate',
    qualityPoints: '407.50',
  },
  {
    gpa: '3.97',
    gpaCreditHours: '146',
    gpaType: 'Overall',
    creditHoursAttempted: '174',
    creditHoursEarned: '174',
    creditHoursPassed: '174',
    level: 'Undergraduate',
    qualityPoints: '579.50',
  },
];
const rawAccountBalance = {
  identifierField: fakeId,
  currentBalance: '99.99',
};
const rawTransactions = [
  {
    amount: '2850',
    description: 'Ford Loan-Subsidized',
    entryDate: '2016-12-31 12:29:54',
    category: 'Continuing Education',
    term: '201901',
    transactionType: 'payment',
  },
  {
    amount: '1814',
    description: 'Presidential Scholar 001100',
    entryDate: '2017-11-12 12:13:42',
    category: 'Cascades Campus',
    term: '201903',
    transactionType: 'charge',
  },
];
const rawAcademicStatus = [
  {
    academicStanding: 'Good Standing',
    term: '201803',
    termDescription: 'Spring 2018',
    gpa: '4.00',
    gpaCreditHours: '14',
    gpaType: 'Institution',
    creditHoursAttempted: '14',
    creditHoursEarned: '14',
    creditHoursPassed: '14',
    level: 'Undergraduate',
    qualityPoints: '56.00',
  },
  {
    academicStanding: 'Good Standing',
    term: '201901',
    termDescription: 'Fall 2018',
    gpa: '4.00',
    gpaCreditHours: '15',
    gpaType: 'Institution',
    creditHoursAttempted: '16',
    creditHoursEarned: '16',
    creditHoursPassed: '16',
    level: 'Undergraduate',
    qualityPoints: '60.00',
  },
];
const rawClassification = {
  identifierField: fakeId,
  level: 'Graduate',
  classification: 'Determine from Student Type',
  status: 'New Student',
  isInternational: 'Y',
  campusCode: 'C',
  campus: 'Oregon State - Corvallis',
};
const rawGrades = [
  {
    identifierField: `${fakeId}-200803-37626`,
    courseReferenceNumber: '37626',
    gradeFinal: 'A',
    courseSubject: 'SPAN',
    courseSubjectDescription: 'Spanish',
    courseNumber: '336',
    courseTitle: '*LATIN AMERICAN CULTURE',
    sectionNumber: '001',
    term: '200803',
    termDescription: 'Spring 2008',
    scheduleType: 'A',
    scheduleDescription: 'Lecture',
    creditHours: '3',
    tcknCourseLevel: 'Non-Degree / Credential',
    sfrstcrCourseLevel: null,
    registrationStatus: null,
    gradeMode: 'N',
    gradeModeDescription: 'Normal Grading Mode',
  },
  {
    identifierField: `${fakeId}-201900-72004`,
    courseReferenceNumber: '72004',
    gradeFinal: 'B',
    courseSubject: 'FW',
    courseSubjectDescription: 'Fisheries and Wildlife',
    courseNumber: '427',
    courseTitle: 'PRINCIPLES OF WILDLIFE DISEASE',
    sectionNumber: '400',
    term: '201900',
    termDescription: 'Summer 2018',
    scheduleType: 'Y',
    scheduleDescription: 'Online',
    creditHours: '4',
    tcknCourseLevel: 'Undergraduate',
    sfrstcrCourseLevel: 'E-Campus Undergraduate Course',
    registrationStatus: '**Web Registered**',
    gradeMode: 'N',
    gradeModeDescription: 'Normal Grading Mode',
  },
];
const rawClassSchedule = [
  {
    academicYear: '0405',
    academicYearDescription: 'Academic Year 2004-05',
    courseReferenceNumber: '37430',
    courseSubject: 'RNG',
    courseSubjectDescription: 'Rangeland Ecology & Management',
    courseNumber: '399',
    courseTitleShort: 'SPECIAL TOPICS',
    courseTitleLong: null,
    sectionNumber: '001',
    term: '200503',
    termDescription: 'Spring 2005',
    scheduleType: 'F',
    scheduleDescription: 'Independent or Special Studies',
    creditHours: '2',
    registrationStatus: '**Web Registered**',
    gradingMode: 'Normal Grading Mode',
    continuingEducation: null,
    facultyOsuId: '930608969',
    facultyName: 'Ehrhart, Robert',
    facultyEmail: 'Bob.Ehrhart@oregonstate.edu',
    facultyPrimary: 'Y',
    beginDate: '2005-03-28',
    beginTime: null,
    endDate: '2005-06-03',
    endTime: null,
    room: null,
    building: null,
    buildingDescription: null,
    campusCode: 'B',
    campus: 'Oregon State - Cascades',
    hoursPerWeek: '0',
    creditHourSession: '2',
    meetingScheduleType: 'F',
    meetingScheduleDescription: 'Independent or Special Studies',
    monday: null,
    tuesday: null,
    wednesday: null,
    thursday: null,
    friday: null,
    saturday: null,
    sunday: null,
  },
  {
    academicYear: '0405',
    academicYearDescription: 'Academic Year 2004-05',
    courseReferenceNumber: '35301',
    courseSubject: 'BIO',
    courseSubjectDescription: 'Biology-UO',
    courseNumber: '370-U',
    courseTitleShort: 'UO. ECOLOGY',
    courseTitleLong: null,
    sectionNumber: '001',
    term: '200503',
    termDescription: 'Spring 2005',
    scheduleType: 'A',
    scheduleDescription: 'Lecture',
    creditHours: '4',
    registrationStatus: '**Web Registered**',
    gradingMode: 'Normal Grading Mode',
    continuingEducation: null,
    facultyOsuId: '930828000',
    facultyName: 'Clark, Lisa',
    facultyEmail: null,
    facultyPrimary: 'Y',
    beginDate: '2005-03-28',
    beginTime: '1900',
    endDate: '2005-06-03',
    endTime: '2030',
    room: '201',
    building: 'CSB',
    buildingDescription: 'Cascades Hall (COOSU)',
    campusCode: 'B',
    campus: 'Oregon State - Cascades',
    hoursPerWeek: '3',
    creditHourSession: '4',
    meetingScheduleType: 'A',
    meetingScheduleDescription: 'Lecture',
    monday: null,
    tuesday: 'T',
    wednesday: null,
    thursday: 'R',
    friday: null,
    saturday: null,
    sunday: null,
  },
];
const rawHolds = [
  {
    fromDate: '2011-12-28',
    toDate: '2099-12-31',
    reason: 'ACTG 321',
    description: 'Missing Requirements',
    registration: null,
    transcript: null,
    graduation: 'Graduation',
    grades: null,
    accountsReceivable: null,
    enrollmentVerification: null,
    application: null,
    compliance: null,
    code: 'N3',
    releasedInd: null,
    organizationCode: 'TUDY',
    organizationDescription: 'Tudy/Registrar\'s Office',
  },
  {
    fromDate: '2011-12-28',
    toDate: '2099-12-31',
    reason: 'Has not applied as Postbac',
    description: 'Must Apply as Postbac',
    registration: 'Registration',
    transcript: null,
    graduation: 'Graduation',
    grades: null,
    accountsReceivable: null,
    enrollmentVerification: null,
    application: null,
    compliance: null,
    code: 'AS',
    releasedInd: 'Y',
    organizationCode: 'GRDN',
    organizationDescription: 'Graduate Dean',
  },
];
const rawAwards = [
  {
    offerAmount: '1500',
    offerExpirationDate: '2006-06-09',
    acceptedAmount: '1500',
    acceptedDate: '2006-05-12',
    paidAmount: '0',
    awardStatus: 'Accepted',
    effectiveStartDate: '2006-09-25',
    effectiveEndDate: '2007-06-15',
  },
  {
    offerAmount: '0',
    offerExpirationDate: null,
    acceptedAmount: '0',
    acceptedDate: null,
    paidAmount: '0',
    awardStatus: 'Cancelled',
    effectiveStartDate: '2007-06-25',
    effectiveEndDate: '2008-03-21',
  },
];
const rawDualEnrollment = [
  {
    identifierField: `${fakeId}-200503`,
    creditHours: '5',
    term: '200503',
  },
  {
    identifierField: `${fakeId}-200602`,
    creditHours: '8',
    term: '200602',
  },
  {
    identifierField: `${fakeId}-200603`,
    creditHours: '8',
    term: '200603',
  },
  {
    identifierField: `${fakeId}-201900`,
    creditHours: '0',
    term: '201900',
  },
  {
    identifierField: `${fakeId}-201901`,
    creditHours: '0',
    term: '201901',
  },
];
const rawDegrees = [
  {
    identifierField: `${fakeId}-201500-1`,
    term: '201500',
    termDescription: 'Summer 2014',
    academicYear: '1415',
    academicYearDescription: 'Academic Year 2014-15',
    programNumber: '1',
    primaryDegree: 'Y',
    college: 'College of Liberal Arts',
    degree: 'Bachelor of Arts',
    level: 'Undergraduate',
    degreeAwardCategory: 'Baccalaureate Degree',
    firstMajor: 'Pre-Communication',
    firstProgramClassification: 'Speech and Rhetorical Studies',
    firstDepartment: 'School of Arts and Comm',
    firstMajorFirstConcentration: null,
    firstMajorSecondConcentration: null,
    firstMajorThirdConcentration: null,
    secondMajor: null,
    secondProgramClassification: null,
    secondDepartment: null,
    secondMajorFirstConcentration: null,
    secondMajorSecondConcentration: null,
    secondMajorThirdConcentration: null,
    thirdMajor: null,
    thirdProgramClassification: null,
    thirdDepartment: null,
    thirdMajorFirstConcentration: null,
    thirdMajorSecondConcentration: null,
    thirdMajorThirdConcentration: null,
    fourthMajor: null,
    fourthProgramClassification: null,
    fourthDepartment: null,
    fourthMajorFirstConcentration: null,
    fourthMajorSecondConcentration: null,
    fourthMajorThirdConcentration: null,
    firstMinor: null,
    secondMinor: null,
    thirdMinor: null,
    fourthMinor: null,
  },
  {
    identifierField: `${fakeId}-201500-2`,
    term: '201500',
    termDescription: 'Summer 2014',
    academicYear: '1415',
    academicYearDescription: 'Academic Year 2014-15',
    programNumber: '2',
    primaryDegree: 'N',
    college: 'College of Liberal Arts',
    degree: 'Bachelor of Arts',
    level: 'Undergraduate',
    degreeAwardCategory: 'Baccalaureate Degree',
    firstMajor: 'International Studies',
    firstProgramClassification: 'International Studies',
    firstDepartment: 'International Degree',
    firstMajorFirstConcentration: null,
    firstMajorSecondConcentration: null,
    firstMajorThirdConcentration: null,
    secondMajor: null,
    secondProgramClassification: null,
    secondDepartment: null,
    secondMajorFirstConcentration: null,
    secondMajorSecondConcentration: null,
    secondMajorThirdConcentration: null,
    thirdMajor: null,
    thirdProgramClassification: null,
    thirdDepartment: null,
    thirdMajorFirstConcentration: null,
    thirdMajorSecondConcentration: null,
    thirdMajorThirdConcentration: null,
    fourthMajor: null,
    fourthProgramClassification: null,
    fourthDepartment: null,
    fourthMajorFirstConcentration: null,
    fourthMajorSecondConcentration: null,
    fourthMajorThirdConcentration: null,
    firstMinor: null,
    secondMinor: null,
    thirdMinor: null,
    fourthMinor: null,
  },
  {
    identifierField: `${fakeId}-201501-1`,
    term: '201501',
    termDescription: 'Fall 2014',
    academicYear: '1415',
    academicYearDescription: 'Academic Year 2014-15',
    programNumber: '1',
    primaryDegree: 'Y',
    college: 'College of Liberal Arts',
    degree: 'Bachelor of Arts',
    level: 'Undergraduate',
    degreeAwardCategory: 'Baccalaureate Degree',
    firstMajor: 'Speech Communication',
    firstProgramClassification: 'Speech Communication',
    firstDepartment: 'School of Arts and Comm',
    firstMajorFirstConcentration: 'Communication',
    firstMajorSecondConcentration: null,
    firstMajorThirdConcentration: null,
    secondMajor: null,
    secondProgramClassification: null,
    secondDepartment: null,
    secondMajorFirstConcentration: null,
    secondMajorSecondConcentration: null,
    secondMajorThirdConcentration: null,
    thirdMajor: null,
    thirdProgramClassification: null,
    thirdDepartment: null,
    thirdMajorFirstConcentration: null,
    thirdMajorSecondConcentration: null,
    thirdMajorThirdConcentration: null,
    fourthMajor: null,
    fourthProgramClassification: null,
    fourthDepartment: null,
    fourthMajorFirstConcentration: null,
    fourthMajorSecondConcentration: null,
    fourthMajorThirdConcentration: null,
    firstMinor: null,
    secondMinor: null,
    thirdMinor: null,
    fourthMinor: null,
  },
  {
    identifierField: `${fakeId}-201501-2`,
    term: '201501',
    termDescription: 'Fall 2014',
    academicYear: '1415',
    academicYearDescription: 'Academic Year 2014-15',
    programNumber: '2',
    primaryDegree: 'N',
    college: 'College of Liberal Arts',
    degree: 'Bachelor of Arts',
    level: 'Undergraduate',
    degreeAwardCategory: 'Baccalaureate Degree',
    firstMajor: 'International Studies',
    firstProgramClassification: 'International Studies',
    firstDepartment: 'International Degree',
    firstMajorFirstConcentration: null,
    firstMajorSecondConcentration: null,
    firstMajorThirdConcentration: null,
    secondMajor: null,
    secondProgramClassification: null,
    secondDepartment: null,
    secondMajorFirstConcentration: null,
    secondMajorSecondConcentration: null,
    secondMajorThirdConcentration: null,
    thirdMajor: null,
    thirdProgramClassification: null,
    thirdDepartment: null,
    thirdMajorFirstConcentration: null,
    thirdMajorSecondConcentration: null,
    thirdMajorThirdConcentration: null,
    fourthMajor: null,
    fourthProgramClassification: null,
    fourthDepartment: null,
    fourthMajorFirstConcentration: null,
    fourthMajorSecondConcentration: null,
    fourthMajorThirdConcentration: null,
    firstMinor: null,
    secondMinor: null,
    thirdMinor: null,
    fourthMinor: null,
  },
];

module.exports = {
  fakeId,
  fakeBaseUrl,
  fakeType,
  fakePath,
  fakeDefinitions,
  argsTestCases,
  rawGpaLevels,
  rawAccountBalance,
  rawTransactions,
  rawAcademicStatus,
  rawClassification,
  rawGrades,
  rawClassSchedule,
  rawHolds,
  rawAwards,
  rawDualEnrollment,
  rawDegrees,
};
